---
- name: Add greek repo
  apt_repository: repo=ppa:ts.sch.gr state=present update_cache=yes

- name: Install ltsp-pnp packages
  apt: pkg={{ item }} state=present
  with_items:
  - ltsp-client
  - ltsp-server
  - ldm-ubuntu-theme
  register: install

- name: Install a GUI
  apt: pkg=lxde-core state=present

- name: Build client image
  debug: install
  notify: ltsp-image
  when: install.changed

- name: Install a default lts.conf
  copy: src=lts.conf dest=/var/lib/tftpboot/ltsp/amd64/lts.conf owner=root group=root mode=0644
